name: Build and Release ESP32-C3 Firmware

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Move File for Build
        run: |
          mkdir -p src
          cp *.ino src/main.cpp || cp *.cpp src/main.cpp

      - name: Run PlatformIO Build
        run: pio run

      - name: Delete old Release
        run: gh release delete latest --yes || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        run: |
          gh release create latest \
            .pio/build/esp32-c3-devkitm-1/firmware.bin \
            --title "Latest" \
            --notes "Auto build" \
            --latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
