[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; ওটিএ আপডেট সচল রাখতে এই পার্টিশনটি জরুরি
board_build.partitions = huge_app.csv

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit BusIO @ ^1.14.1
    bblanchon/ArduinoJson @ ^6.21.2
    arduino-libraries/NTPClient @ ^3.2.1
    ; ESP32 এর ডিফল্ট লাইব্রেরিগুলো নিচে লিস্ট করা হলো (বিল্ড সহজ করতে)
    WiFi
    HTTPClient
    HTTPUpdate
    WebServer
    DNSServer
    ESPmDNS
    Wire
    SPI
