[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; ওটিএ (OTA) আপডেটের জন্য মেমোরিতে বেশি জায়গা দিতে এই সেটিংস জরুরি
board_build.partitions = huge_app.csv

; আপনার কোডে ব্যবহৃত লাইব্রেরিগুলো এখানে লিস্ট করা হয়েছে
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit BusIO @ ^1.14.1
    bblanchon/ArduinoJson @ ^6.21.2
    Wire
    SPI
